name: ball_on_a_budget_planner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  flutter_bloc: ^6.1.3
  bloc: ^6.1.3

  flutter_spinkit: ^5.0.0
  easy_localization: ^3.0.0
  carousel_pro: ^1.0.0
  intl: ^0.17.0-nullsafety.2
  font_awesome_flutter: ^9.0.0
  rxdart: ^0.26.0
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5
  flutter_masked_text: ^0.8.0
  fl_chart: ^0.35.0
  flutter_circular_chart_two: ^0.1.2
  date_format: ^2.0.2
  flutter_speed_dial: ^3.0.5
  jiffy: ^4.1.0
  flutter_local_notifications: ^5.0.0+1
  package_info: ^2.0.0
  analog_clock: ^0.0.4
  
  
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.1
  cloud_firestore: ^1.0.2
  firebase_core: ^1.0.2
  google_fonts: ^2.0.0

  flutter_secure_storage: ^4.1.0
  
  
  flutter_facebook_login: ^3.0.0
  
  flutter_launcher_icons: ^0.9.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: "launcher_icon"
  ios: true


flutter:


  uses-material-design: true
  assets:
   - assets/images/
   - assets/translations/
   - icons/
  fonts:
   - family: BanklinIcons
     fonts:
      - asset: assets/fonts/BanklinIcons.ttf
